apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd 
  
spec:
  project: default

  source:
    repoURL: http://18.205.184.214/root/test-project.git
    targetRevision: argocd-deployment
    path: k8s-manifests 

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
